---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: ex-dra-driver
  name: nx-gzip
spec:
  spec:
    devices:
      requests:
      - name: nx-gzip
        deviceClassName: nx.device.power.ibm.com

---
apiVersion: v1
kind: Pod
metadata:
  namespace: ex-dra-driver
  name: pod0
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0
  containers:
  - name: ctr0
    image: quay.io/powercloud/power-dra-driver:main
    command: ["/opt/power-dra/bin/power-dra-kubeletplugin"]
    args:
      - "--node-name=worker-0"
    resources:
      claims:
      - name: nx-gzip
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      runAsUser: 0
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  resourceClaims:
  - name: nx-gzip
    resourceClaimTemplateName: nx-gzip

---
apiVersion: v1
kind: Pod
metadata:
  namespace: ex-dra-driver
  name: pod1
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0
  containers:
  - name: ctr0
    image: quay.io/powercloud/power-dra-driver:main
    command: ["/opt/power-dra/bin/power-dra-kubeletplugin"]
    args:
      - "--node-name=worker-0"
    resources:
      claims:
      - name: nx-gzip
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      runAsUser: 0
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  resourceClaims:
  - name: nx-gzip
    resourceClaimTemplateName: nx-gzip