---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: ex-power-dra
  name: nx-gzip-template-0
spec:
  spec:
    devices:
      requests:
      - name: nx-gzip
        deviceClassName: nx.device.power.ibm.com

---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: ex-power-dra
  name: nx-gzip-template-1
spec:
  spec:
    devices:
      requests:
      - name: nx-gzip
        deviceClassName: nx.device.power.ibm.com