apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nx-device-plugin
  namespace: kube-system
  labels:
    app: nx-device-plugin
spec:
  selector:
    matchLabels:
      app: nx-device-plugin
  template:
    metadata:
      labels:
        app: nx-device-plugin
    spec:
      serviceAccount: ex-sa
      serviceAccountName: ex-sa
      securityContext:
        fsGroup: 0
      containers:
        - name: nx-device-plugin
          image: quay.io/powercloud/power-dra-driver:main
          imagePullPolicy: IfNotPresent
          command: ["/opt/power-dra/bin/power-dra-kubeletplugin"]
          args:
            - "--node-name=worker-0"
            - "--cdi-root=/cdi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: device-plugins
              mountPath: /var/lib/kubelet/plugins
            - name: cdi-dir
              mountPath: /cdi
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/plugins
            type: DirectoryOrCreate
        - name: cdi-dir
          emptyDir: {}